Mvc/NotesMarketPlaces/NotesMarketPlaces/Controllers/AdminReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NotesMarketPlaces.Models;
using NotesMarketPlaces.ViewModels;

namespace NotesMarketPlaces.Controllers
{
    
    [RoutePrefix("Admin")]
    [OutputCache(Duration = 0)]
    public class AdminReportsController : Controller
    {

        readonly private NotesMarketPlaceEntities1 _dbContext = new NotesMarketPlaceEntities1();

        // GET: AdminReports
        [HttpGet]
        [Authorize(Roles ="SuperAdmin,Admin")]
        [Route("SpamReports")]
        public ActionResult SpamReports(string search,string sortby,string sortorder,int page=1)
        {
            ViewBag.SpamRepotsSearch = search;
            ViewBag.PageNumber = page;
            ViewBag.SortBy = sortby;
            ViewBag.SortOrder = sortorder;

            IEnumerable<AdminSpamRecordsViewModel> spamlist;
            spamlist = from reports in _dbContext.SellerNotesReportedIssues
                       join creatby in _dbContext.Users on reports.ReportedBYID equals creatby.ID
                       join note in _dbContext.SellerNotes on reports.NoteID equals note.ID
                       where note.IsActive == true
                       select new AdminSpamRecordsViewModel { 
                           Category=note.NotesCategory.Name,
                           NoteID=note.ID,
                           NoteTitle=note.Title,
                           Remark=reports.Remark,
                           ReportedBy=creatby.FirstName+" "+creatby.LastName,
                           SpamID=reports.ID,
                           DateEdited=reports.CreatedDate
                       };
            if (!string.IsNullOrEmpty(search))
            {
                search = search.ToLower();
                spamlist = spamlist.Where(x => x.NoteTitle.ToLower().Contains(search) ||
                                             x.Remark.ToLower().Contains(search) ||
                                             x.ReportedBy.ToLower().Contains(search) ||
                                             x.Category.ToLower().Contains(search) ||
                                             x.NoteTitle.ToLower().Contains(search)||
                                             x.DateEdited.Value.ToString("dd-MM-yyyy,hh:mm").Contains(search)).ToList();
            }
            //Count total page
            ViewBag.TotalPages = Math.Ceiling(spamlist.Count() / 5.0);
            spamlist = spamlist.Skip((page - 1) * 5).Take(5);
            //Going for sorting
            spamlist = SortTableSpamReports(sortby, sortorder, spamlist);

            return View(spamlist);
        }

        private IEnumerable<AdminSpamRecordsViewModel> SortTableSpamReports(string sortby, string sortorder, IEnumerable<AdminSpamRecordsViewModel> table)
        {
            switch (sortby)
            {
                case "Category":
                    {
                        switch (sortorder)
                        {
                            case "Asc":
                                {
                                    table = table.OrderBy(x => x.Category);
                                    return table;
                                }
                            case "Desc":
                                {
                                    table = table.OrderByDescending(x => x.Category);
                                    return table;
                                }
                            default:
                                {
                                    table = table.OrderBy(x => x.Category);
                                    return table;
                                }
                        }
                    }
                case "Remark":
                    {
                        switch (sortorder)
                        {
                            case "Asc":
                                {
                                    table = table.OrderBy(x => x.Remark);
                                    return table;
                                }
                            case "Desc":
                                {
                                    table = table.OrderByDescending(x => x.Remark);
                                    return table;
                                }
                            default:
                                {
                                    table = table.OrderBy(x => x.Remark);
                                    return table;
                                }
                        }
                    }
                case "NoteTitle":
                    {
                        switch (sortorder)
                        {
                            case "Asc":
                                {
                                    table = table.OrderBy(x => x.NoteTitle);
                                    return table;
                                }
                            case "Desc":
                                {
                                    table = table.OrderByDescending(x => x.NoteTitle);
                                    return table;
                                }
                            default:
                                {
                                    table = table.OrderBy(x => x.NoteTitle);
                                    return table;
                                }
                        }
                    }

                case "DateEdited":
                    {
                        switch (sortorder)
                        {
                            case "Asc":
                                {
                                    table = table.OrderBy(x => x.DateEdited);
                                    return table;
                                }
                            case "Desc":
                                {
                                    table = table.OrderByDescending(x => x.DateEdited);
                                    return table;
                                }
                            default:
                                {
                                    table = table.OrderBy(x => x.DateEdited);
                                    return table;
                                }
                        }
                    }
                case "ReportedBy":
                    {
                        switch (sortorder)
                        {
                            case "Asc":
                                {
                                    table = table.OrderBy(x => x.ReportedBy);
                                    return table;
                                }
                            case "Desc":
                                {
                                    table = table.OrderByDescending(x => x.ReportedBy);
                                    return table;
                                }
                            default:
                                {
                                    table = table.OrderBy(x => x.ReportedBy);
                                    return table;
                                }
                        }
                    }

                default:
                    {
                        switch (sortorder)
                        {
                            case "Asc":
                                {
                                    table = table.OrderBy(x => x.Category);
                                    return table;
                                }
                            case "Desc":
                                {
                                    table = table.OrderByDescending(x => x.Category);
                                    return table;
                                }
                            default:
                                {
                                    table = table.OrderBy(x => x.Category);
                                    return table;
                                }
                        }
                    }
            }
        }
        [Authorize(Roles ="SuperAdmin,Admin")]
        [HttpGet]
        [Route("SpamReports/Delete/{id}")]
        public ActionResult DeleteSpam(int id)
        {
            //Find spam note in database
            var spam = _dbContext.SellerNotesReportedIssues.Where(x => x.ID == id).FirstOrDefault();
            if (spam == null)
            {
                return HttpNotFound();
            }
            _dbContext.SellerNotesReportedIssues.Remove(spam);
            _dbContext.SaveChanges();
            return RedirectToAction("SpamReports");
        }
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminReports/SpamReports.cshtml
@model IEnumerable<NotesMarketPlaces.ViewModels.AdminSpamRecordsViewModel>
@{
    ViewBag.Title = "Spam Reports";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Spam Records-->
<section id="spam-records">
    <div class="container">
        <div class="content-box-md">
            @using (Html.BeginForm("SpamReports", "AdminReports", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-lg-7 col-md-7 col-sm-5 heading  my-auto">Spam Records</div>

                    <div class="col-lg-5 col-md-5 col-sm-7 col-12">
                        <div class="row search" id="table-search">
                            <div class="search-bar col-lg-9 col-md-9 col-sm-9 col-9 form-group">
                                <input type="search" class="form-control" id="search" placeholder="Search" name="search" value="@ViewBag.SpamRepotsSearch">
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-3 btn-search">
                                <button class="btn btn-color" type="submit" title="Search" role="button">Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="row table-general table-responsive">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Sr no.</th>
                                <th>@Html.ActionLink("Reported By", "SpamReports", new { sortorder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), sortby = "ReportedBy" })</th>
                                <th>@Html.ActionLink("Note Title", "SpamReports", new { sortorder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), sortby = "NoteTitle" })</th>
                                <th>@Html.ActionLink("Category", "SpamReports", new { sortorder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), sortby = "Category" })</th>
                                <th>@Html.ActionLink("Date Edited", "SpamReports", new { sortorder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), sortby = "DateEdited" })</th>
                                <th>@Html.ActionLink("Remark", "SpamReports", new { sortorder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), sortby = "Remark" })</th>
                                <th>Action</th>
                                <th class="content-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count() == 0)
                            {
                                <tr class="content-center">
                                    <td colspan="8">No Record Found</td>
                                </tr>
                            }
                            else
                            {
                                var srno = (ViewBag.PageNumber - 1) * 5;
                                foreach (var item in Model)
                                {
                                    { srno = srno + 1; }
                                    <tr>
                                        <th scope="row">@srno</th>
                                        <td>@item.ReportedBy</td>
                                        <td>@item.NoteTitle</td>
                                        <td>@item.Category</td>
                                        <td>@item.DateEdited.Value.ToString("dd-MM-yyyy,hh:mm")</td>
                                        <td>@item.Remark</td>
                                        <td class="content-center">
                                            <div class="table-images">
                                                <button type="button" class="btn" aria-haspopup="true" aria-expanded="false" data-toggle="modal" data-target="#confirmation-@item.SpamID">
                                                    <img src="~/Image/images/Dashboard/delete.png" alt="delete" class="delete">
                                                </button>
                                            </div>
                                        </td>
                                        <td class="content-center">
                                            <div class="table-images">
                                                <div class="btn-group dropleft">
                                                    <button type="button" id="dropdownMenu2" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <img src="~/Image/images/icon/dots.png" alt="menu" class="dots">
                                                    </button>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                                        <a class="dropdown-item" type="button" href="@Url.Action("AdminDownloadNote","Admin",new { noteid=item.NoteID})">Download Note</a>
                                                        <a class="dropdown-item" type="button" href="@Url.Action("AdminNoteDetails","Admin",new { noteid=item.NoteID})">View More Details</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <!-- Confirmation -->
                                    <div class="modal fade" id="confirmation-@item.SpamID" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-body" style="margin-top:10px">
                                                    <div class="text-center">
                                                        <h5 style="color:black">Are you sure you want to delete reported issue?</h5>
                                                    </div>

                                                    <div class="text-center">
                                                        <a class="btn btn-primary" href="@Url.Action("DeleteSpam","AdminReports",new { id=item.SpamID})">Yes</a>
                                                        <button class="btn btn-default" data-dismiss="modal" aria-label="Close">No</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End Confirmation-->
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            
            @if (Model.Count() != 0)
            {
                <div class="row justify-content-center">

                    <nav aria-label="...">
                        <ul class="pagination flex-wrap">

                            <li class="page-item">
                                @if (ViewBag.PageNumber == 1)
                                {
                                    <a class="page-link" href="@Url.Action("SpamReports", new { sellername = ViewBag.SellerName, sortby=@ViewBag.SortBy,sortorder=@ViewBag.SortOrder,search=@ViewBag.SpamRepotsSearch,  page = ViewBag.PageNumber })"><i class="fa fa-angle-left"></i></a>
                                }
                                else
                                {
                                    <a class="page-link" href="@Url.Action("SpamReports", new { sellername = ViewBag.SellerName, note = ViewBag.Note, sortby=@ViewBag.SortBy,sortorder=@ViewBag.SortOrder, search=@ViewBag.SpamRepotsSearch, page = @ViewBag.PageNumber - 1 })"><i class="fa fa-angle-left"></i></a>
                                }
                            </li>

                            @{
                                double? TotalPages = ViewBag.TotalPages;

                                if (ViewBag.PageNumber != 1 && ViewBag.PageNumber - 2 > 1)
                                {
                                    int page = Convert.ToInt32(@ViewBag.PageNumber) - 3;
                                    <li class="page-item">@Html.ActionLink("1", "SpamReports", new { sortby = @ViewBag.SortBy, sortorder = @ViewBag.SortOrder, search = @ViewBag.SpamRepotsSearch, page = 1 }, new { @class = "page-link" })</li>
                                    if (page != 1)
                                    {
                                        <li class="page-item more-pages-dots">@Html.ActionLink("...", "SpamReports", new { sortby = @ViewBag.SortBy, sortorder = @ViewBag.SortOrder, search = @ViewBag.SpamRepotsSearch, page = page }, new { @class = "page-link more-pages-dots" })</li>
                                    }
                                }

                                for (int i = 2; i > 0; i--)
                                {
                                    if (ViewBag.PageNumber - i > 0)
                                    {
                                        int page = Convert.ToInt32(@ViewBag.PageNumber) - i;
                                        <li class="page-item">@Html.ActionLink(page.ToString(), "SpamReports", new { sortby = @ViewBag.SortBy, sortorder = @ViewBag.SortOrder, search = @ViewBag.SpamRepotsSearch, page = page }, new { @class = "page-link" })</li>
                                    }
                                }

                                <li class="page-item active">
                                    <a class="page-link">@ViewBag.PageNumber<span class="sr-only">(current)</span></a>
                                </li>

                                for (int i = 1; i < 3; i++)
                                {
                                    if (ViewBag.PageNumber + i <= TotalPages)
                                    {
                                        int page = Convert.ToInt32(@ViewBag.PageNumber) + i;
                                        <li class="page-item">@Html.ActionLink(page.ToString(), "SpamReports", new { sortby = @ViewBag.SortBy, sortorder = @ViewBag.SortOrder, search = @ViewBag.SpamRepotsSearch, page = page }, new { @class = "page-link" })</li>
                                    }
                                }

                                if (ViewBag.PageNumber != TotalPages && ViewBag.PageNumber + 2 < TotalPages)
                                {
                                    int page = Convert.ToInt32(@ViewBag.PageNumber) + 3;
                                    if (page != TotalPages)
                                    {
                                        <li class="page-item">@Html.ActionLink("...", "SpamReports", new { sortby = @ViewBag.SortBy, sortorder = @ViewBag.SortOrder, search = @ViewBag.SpamRepotsSearch, page = page }, new { @class = "page-link more-pages-dots" })</li>
                                    }
                                    <li class="page-item">@Html.ActionLink(TotalPages.ToString(), "SpamReports", new { sortby = @ViewBag.SortBy, sortorder = @ViewBag.SortOrder, search = @ViewBag.SpamRepotsSearch, page = TotalPages }, new { @class = "page-link" })</li>
                                }

                            }

                            <li class="page-item">
                                @if (ViewBag.PageNumber == ViewBag.TotalPages)
                                {
                                    <a class="page-link" href="@Url.Action("SpamReports", new { sortby=@ViewBag.SortBy,sortorder=@ViewBag.SortOrder, search=@ViewBag.SpamRepotsSearch, page = @ViewBag.PageNumber })"><i class="fa fa-angle-right"></i></a>
                                }
                                else
                                {
                                    <a class="page-link" href="@Url.Action("SpamReports", new { sortby=@ViewBag.SortBy,sortorder=@ViewBag.SortOrder, search=@ViewBag.SpamRepotsSearch, page = @ViewBag.PageNumber + 1 })"><i class="fa fa-angle-right"></i></a>
                                }
                            </li>

                        </ul>
                    </nav>

                </div>
            }
        </div>
    </div>
</section>
<!--End Published Notes-->