Mvc/NotesMarketPlaces/NotesMarketPlaces/ViewModels/AddCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NotesMarketPlaces.ViewModels
{
    public class AddCategoryViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "This is required")]
        [MaxLength(100, ErrorMessage = "This Name is too long")]
        public string Category { get; set; }

        [Required(ErrorMessage = "This is required")]
        public string Description { get; set; }
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/ViewModels/AddCountryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NotesMarketPlaces.ViewModels
{
    public class AddCountryViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [MaxLength(50, ErrorMessage = "This name is too long")]
        public string CountryName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [MaxLength(50, ErrorMessage = "This name is too long")]
        public string Code { get; set; }

        
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/ViewModels/ManageAdministratorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NotesMarketPlaces.ViewModels
{
    public class ManageAdministratorViewModel
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime? DateAdded { get; set; }
        public string Active { get; set; }
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/ViewModels/ManageCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NotesMarketPlaces.ViewModels
{
    public class ManageCategoryViewModel
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public DateTime? DateAdded { get; set; }
        public string AddedBy { get; set; }
        public string Active { get; set; }
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/ViewModels/ManageCountryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NotesMarketPlaces.ViewModels
{
    public class ManageCountryViewModel
    {
        public int ID { get; set; }
        public string CountryName { get; set; }

        public string CountryCode { get; set; }

        public DateTime? CreatedDate { get; set; }
        public string AddedBy { get; set; }
        public string Active { get; set; }
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/ViewModels/ManageSystemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NotesMarketPlaces.ViewModels
{
    public class ManageSystemViewModel
    {
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Use valid email address")]
        [MaxLength(100, ErrorMessage = "Email is too long")]
        public string SupportEmail { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string SupportContact { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Use valid email address")]
        public string NotifyEmail { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Url]
        public string FacebookURL { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Url]
        public string TwitterURL { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Url]
        public string LinkedInURL { get; set; }
        [Required(ErrorMessage = "This field is required")]

        public HttpPostedFileBase DefaultProfile { get; set; }
        public HttpPostedFileBase DefaultNote { get; set; }

        public string DefaultProfileURL { get; set; }

        public string DefaultNoteURL { get; set; }
    }
}

Mvc/NotesMarketPlaces/NotesMarketPlaces/Controllers/AdminSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NotesMarketPlaces.Models;
using NotesMarketPlaces.ViewModels;

namespace NotesMarketPlaces.Controllers
{
    
    [RoutePrefix("Admin")]
    [OutputCache(Duration = 0)]
    public class AdminSettingsController : Controller
    {
        readonly private NotesMarketPlaceEntities1 _dbContext = new NotesMarketPlaceEntities1();

        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        [Route("Settings/ManageSystemConfiguration")]
        public ActionResult ManageSystem()
        {
            // create object of SystemConfigurationViewModel
            ManageSystemViewModel systemConfiguration = new ManageSystemViewModel();

            // get supportemail
            var supportemail = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "SupportEmail").FirstOrDefault();
            if (supportemail != null)
            {
                systemConfiguration.SupportEmail = supportemail.Value;
            }

            // get supportcontact
            var supportcontact = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "supportcontact").FirstOrDefault();
            if (supportcontact != null)
            {
                systemConfiguration.SupportContact = supportcontact.Value;
            }

            // get notifyemail
            var notifyemail = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "notifyemail").FirstOrDefault();
            if (notifyemail != null)
            {
                systemConfiguration.NotifyEmail = notifyemail.Value;
            }

            // get facebookurl
            var facebookurl = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "facebookurl").FirstOrDefault();
            if (facebookurl != null)
            {
                systemConfiguration.FacebookURL = facebookurl.Value;
            }

            // get twitterurl
            var twitterurl = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "twitterurl").FirstOrDefault();
            if (twitterurl != null)
            {
                systemConfiguration.TwitterURL = twitterurl.Value;
            }

            // get linkedinurl
            var linkedinurl = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "linkedinurl").FirstOrDefault();
            if (linkedinurl != null)
            {
                systemConfiguration.LinkedInURL = linkedinurl.Value;
            }

            // get defaultprofile
            var defaultprofile = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "defaultprofile").FirstOrDefault();
            if (defaultprofile != null)
            {
                systemConfiguration.DefaultProfileURL = defaultprofile.Value;
            }

            // get defaultnote
            var defaultnote = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "defaultnote").FirstOrDefault();
            if (defaultnote != null)
            {
                systemConfiguration.DefaultNoteURL = defaultnote.Value;
            }

            return View(systemConfiguration);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        [Route("Settings/ManageSystem")]
        public ActionResult ManageSystem(ManageSystemViewModel obj)
        {
            // check if default note picture is available or not
            if (obj.DefaultNote == null && obj.DefaultNoteURL == null)
            {
                ModelState.AddModelError("DefaultNote", "Default note picture is required");
                return View(obj);
            }

            // check if default profile picture is available or not
            if (obj.DefaultProfile == null && obj.DefaultProfileURL == null)
            {
                ModelState.AddModelError("DefaultProfile", "Default profile picture is required");
                return View(obj);
            }

            if (ModelState.IsValid)
            {
                // get logged in superadmin
                var superadmin = _dbContext.Users.Where(x => x.EmailID == User.Identity.Name).FirstOrDefault();

                // create object of SystemConfiguration
                SystemConfiguration systemConfiguration = new SystemConfiguration();

                // get supportemail
                var supportemail = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "supportemail").FirstOrDefault();
                // if supportemail is null then create
                if (supportemail == null)
                {
                    systemConfiguration.Key = "SupportEmail";
                    systemConfiguration.Value = obj.SupportEmail.Trim();
                    systemConfiguration.CreatedDate = DateTime.Now;
                    systemConfiguration.CreatedBy = superadmin.ID;
                    systemConfiguration.IsActive = true;

                    _dbContext.SystemConfigurations.Add(systemConfiguration);
                    _dbContext.SaveChanges();
                }
                // edit supportemail
                else
                {
                    if (!supportemail.Value.Equals(obj.SupportEmail))
                    {
                        supportemail.Value = obj.SupportEmail.Trim();
                        supportemail.ModifiedDate = DateTime.Now;
                        supportemail.ModifiedBy = superadmin.ID;

                        _dbContext.Entry(supportemail).State = EntityState.Modified;
                        _dbContext.SaveChanges();
                    }
                }

                // get supportcontact
                var supportcontact = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "supportcontact").FirstOrDefault();
                // if supportcontact is null then create
                if (supportcontact == null)
                {
                    systemConfiguration.Key = "SupportContact";
                    systemConfiguration.Value = obj.SupportContact.Trim();
                    systemConfiguration.CreatedDate = DateTime.Now;
                    systemConfiguration.CreatedBy = superadmin.ID;
                    systemConfiguration.IsActive = true;

                    _dbContext.SystemConfigurations.Add(systemConfiguration);
                    _dbContext.SaveChanges();
                }
                // edit supportcontact
                else
                {
                    if (!supportcontact.Value.Equals(obj.SupportContact))
                    {
                        supportcontact.Value = obj.SupportContact.Trim();
                        supportcontact.ModifiedDate = DateTime.Now;
                        supportcontact.ModifiedBy = superadmin.ID;

                        _dbContext.Entry(supportcontact).State = EntityState.Modified;
                        _dbContext.SaveChanges();
                    }
                }

                // get notifyemail
                var notifyemail = _dbContext.SystemConfigurations.Where(x => x.Value.ToLower() == "notifyemail").FirstOrDefault();
                // if notifyemail is null then create
                if (notifyemail == null)
                {
                    systemConfiguration.Key = "notifyemail";
                    systemConfiguration.Value = obj.NotifyEmail.Trim();
                    systemConfiguration.CreatedDate = DateTime.Now;
                    systemConfiguration.CreatedBy = superadmin.ID;
                    systemConfiguration.IsActive = true;

                    _dbContext.SystemConfigurations.Add(systemConfiguration);
                    _dbContext.SaveChanges();
                }
                // edit notifyemail
                else
                {
                    if (!notifyemail.Value.Equals(obj.NotifyEmail))
                    {
                        notifyemail.Value = obj.NotifyEmail.Trim();
                        notifyemail.ModifiedDate = DateTime.Now;
                        notifyemail.ModifiedBy = superadmin.ID;

                        _dbContext.Entry(notifyemail).State = EntityState.Modified;
                        _dbContext.SaveChanges();
                    }
                }

                // get facebookurl
                var facebookurl = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "facebookurl").FirstOrDefault();
                // if facebookurl is null then create
                if (facebookurl == null)
                {
                    if (obj.FacebookURL != null)
                    {
                        systemConfiguration.Key = "facebookurl";
                        systemConfiguration.Value = obj.FacebookURL.Trim();
                        systemConfiguration.CreatedDate = DateTime.Now;
                        systemConfiguration.CreatedBy = superadmin.ID;
                        systemConfiguration.IsActive = true;

                        _dbContext.SystemConfigurations.Add(systemConfiguration);
                        _dbContext.SaveChanges();
                    }
                }
                // edit facebookurl
                else
                {
                    if (!facebookurl.Value.Equals(obj.FacebookURL))
                    {
                        facebookurl.Value = obj.FacebookURL.Trim();
                        facebookurl.ModifiedDate = DateTime.Now;
                        facebookurl.ModifiedBy = superadmin.ID;

                        _dbContext.Entry(facebookurl).State = EntityState.Modified;
                        _dbContext.SaveChanges();
                    }
                }

                // get twitterurl
                var twitterurl = _dbContext.SystemConfigurations.Where(x => x.Key.ToLower() == "twitterurl").FirstOrDefault();
                // if twitterurl is null then create
                if (twitterurl == null)
                {

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminSettings/AddAdmin.cshtml
@model NotesMarketPlaces.ViewModels.AddAdministrativeViewModel
@{
    ViewBag.Title = "Add Administrative";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Add Administrator-->
<section id="add-administrator">
    <div class="container">
        <div class="content-box-md">
            <div class="row">
                <div class="col-lg-12 col-md-12 heading">Add Administrator</div>
            </div>
            @using (Html.BeginForm("AddAdmin", "AdminSettings", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="fname">First Name*</label>
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @id = "fname", placeholder = "Enter your first name" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="lname">Last Name*</label>
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @id = "lname", placeholder = "Enter your last name" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="email">Email*</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "fname", placeholder = "Enter your email address" ,@type="email"} })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label id="phone">Phone Number</label>
                        <div class="form-row">
                            <div class="col-lg-3 col-md-3 col-sm-4 col-4">
                                @Html.DropDownListFor(model => model.PhoneCode, new SelectList(Model.PhoneCodeList, "CountryCode", "CountryCode", Model.PhoneCode), "Select code", new { @class = "form-control", @id = "countryCode" })
                                @Html.ValidationMessageFor(model => model.PhoneCode, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-lg-9 col-md-9 col-sm-8 col-8">
                                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @id = "phonenumber", placeholder = "Enter your phone number" } })
                                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-1 col-sm-3 col-md-3 col-3">
                        <button class="btn btn-color" title="submit" role="button" type="submit">Submit</button>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!--End Add Administrtor-->

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminSettings/AddCategory.cshtml
@model NotesMarketPlaces.ViewModels.AddCategoryViewModel
@{
    ViewBag.Title = "Add Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Add Category-->
<section id="add-category">
    <div class="container">
        <div class="content-box-md">
            <div class="row">
                <div class="col-lg-12 col-md-12 heading">Add Category</div>
            </div>
            @using (Html.BeginForm("AddCategory", "AdminSettings", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="fname">Category Name*</label>
                        @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control", @id = "cname", placeholder = "Enter your category name" } })
                        @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="description">Description*</label>
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "description", placeholder = "Enter description" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-1 col-md-2 col-sm-3 col-3">
                        <button class="btn btn-color" title="submit" role="button" type="submit">Submit</button>
                    </div>
                </div>
            }
            </div>
    </div>
</section>
<!--End Add Category-->

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminSettings/AddCountry.cshtml
@model NotesMarketPlaces.ViewModels.AddCountryViewModel
@{
    ViewBag.Title = "Add Country";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Add Country-->
<section id="add-country">
    <div class="container">
        <div class="content-box-md">
            <div class="row">
                <div class="col-lg-12  col-md-12 col-12 heading">Add Country</div>
            </div>
            @using (Html.BeginForm("AddCountry", "AdminSettings", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="fname">Country Name*</label>
                        @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control", @id = "cname", placeholder = "Enter your country name" } })
                        @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
                        
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="description">Contry Code*</label>
                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @id = "code", placeholder = "Enter your country code" } })
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-1 col-md-2 col-sm-3 col-3">
                        <button class="btn btn-color" title="submit" role="button" type="submit">Submit</button>
                    </div>
                </div>
            }
            </div>
    </div>
</section>
<!--End Add Country-->

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminSettings/AddTypes.cshtml
@model NotesMarketPlaces.ViewModels.AddTypesViewModel
@{
    ViewBag.Title = "Add Types";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Add Type-->
<section id="add-type">
    <div class="container">
        <div class="content-box-md">
            <div class="row">
                <div class="col-lg-12 col-md-12 heading">Add Type</div>
            </div>
            @using (Html.BeginForm("AddTypes", "AdminSettings", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="type">Type*</label>
                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", @id = "type", placeholder = "Enter your Type name" } })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="description">Description*</label>
                        @Html.TextAreaFor(model => model.Description,new { @class = "form-control", @id = "description", placeholder = "Enter description" } )
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-1 col-md-2 col-sm- col-4">
                        <button class="btn btn-color" title="submit" role="button" type="submit">Submit</button>
                    </div>
                </div>
            }
            </div>
    </div>
</section>
<!--End Add type-->

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminSettings/EditAdmin.cshtml
@model NotesMarketPlaces.ViewModels.AddAdministrativeViewModel
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Add Administrator-->
<section id="add-administrator">
    <div class="container">
        <div class="content-box-md">
            <div class="row">
                <div class="col-lg-12 col-md-12 heading">Add Administrator</div>
            </div>
            @using (Html.BeginForm("EditAdmin", "AdminSettings", FormMethod.Post))
            {
                @Html.HiddenFor(model => model.UserID)
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="fname">First Name*</label>
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @id = "fname", placeholder = "Enter your first name" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="lname">Last Name*</label>
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @id = "lname", placeholder = "Enter your last name" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="email">Email*</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "fname", placeholder = "Enter your email address", @type = "email" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label id="phone">Phone Number</label>
                        <div class="form-row">
                            <div class="col-lg-3 col-md-3 col-sm-4 col-4">
                                @Html.DropDownListFor(model => model.PhoneCode, new SelectList(Model.PhoneCodeList, "CountryCode", "CountryCode", Model.PhoneCode), "Select code", new { @class = "form-control", @id = "countryCode" })
                                @Html.ValidationMessageFor(model => model.PhoneCode, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-lg-9 col-md-9 col-sm-8 col-8">
                                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @id = "phonenumber", placeholder = "Enter your phone number" } })
                                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-1 col-sm-3 col-md-3 col-3">
                        <button class="btn btn-color" title="submit" role="button" type="submit">Submit</button>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!--End Add Adminis

Mvc/NotesMarketPlaces/NotesMarketPlaces/Views/AdminSettings/EditCategory.cshtml
@model NotesMarketPlaces.ViewModels.AddCategoryViewModel
@{
    ViewBag.Title = "Edit Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!--Blank-->
<section class="blank"></section>
<!--End Blank-->
<!--Add Category-->
<section id="add-category">
    <div class="container">
        <div class="content-box-md">
            <div class="row">
                <div class="col-lg-12 col-md-12 heading">Add Category</div>
            </div>
            @using (Html.BeginForm("EditCategory", "AdminSettings", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model=>model.ID)
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="fname">Category Name*</label>
                        @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control", @id = "cname", placeholder = "Enter your category name" } })
                        @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-8 col-sm-9 col-12">
                        <label for="description">Description*</label>
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "description", placeholder = "Enter description" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-1 col-md-2 col-sm-3 col-3">
                        <button class="btn btn-color" title="submit" role="button" type="submit">Submit</button>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!--End Add Category-->